import 'job_model.dart';

List<Job> sampleJobs = [
  // SSC
  Job(
    title: 'SSC CGL 2026 - Combined Graduate Level',
    organization: 'Staff Selection Commission',
    location: 'All India',
    lastDate: '30 June 2026',
    category: 'SSC',
    applyLink: 'https://ssc.gov.in',
  ),
  Job(
    title: 'SSC CHSL 2026 - 10+2 Level Posts',
    organization: 'Staff Selection Commission',
    location: 'All India',
    lastDate: '05 August 2026',
    category: 'SSC',
    applyLink: 'https://ssc.gov.in',
  ),

  // Railway
  Job(
    title: 'RRB NTPC Graduate Level Posts',
    organization: 'Railway Recruitment Board',
    location: 'All India',
    lastDate: '15 July 2026',
    category: 'Railway',
    applyLink: 'https://indianrailways.gov.in',
  ),
  Job(
    title: 'RRB Group D Recruitment 2026',
    organization: 'Railway Recruitment Board',
    location: 'All India',
    lastDate: '12 August 2026',
    category: 'Railway',
    applyLink: 'https://indianrailways.gov.in',
  ),

  // UPSC
  Job(
    title: 'UPSC Civil Services Examination 2026',
    organization: 'Union Public Service Commission',
    location: 'All India',
    lastDate: '10 August 2026',
    category: 'UPSC',
    applyLink: 'https://upsc.gov.in',
  ),
  Job(
    title: 'UPSC NDA and NA Examination 2026',
    organization: 'Union Public Service Commission',
    location: 'All India',
    lastDate: '30 August 2026',
    category: 'UPSC',
    applyLink: 'https://upsc.gov.in',
  ),

  // Banking
  Job(
    title: 'IBPS PO Recruitment 2026',
    organization: 'Institute of Banking Personnel Selection',
    location: 'All India',
    lastDate: '20 July 2026',
    category: 'Banking',
    applyLink: 'https://ibps.in',
  ),
  Job(
    title: 'SBI Clerk Recruitment 2026',
    organization: 'State Bank of India',
    location: 'All India',
    lastDate: '18 August 2026',
    category: 'Banking',
    applyLink: 'https://sbi.co.in/careers',
  ),

  // Defence
  Job(
    title: 'Indian Army - Technical Entry Scheme',
    organization: 'Indian Army',
    location: 'All India',
    lastDate: '25 July 2026',
    category: 'Defence',
    applyLink: 'https://joinindianarmy.nic.in',
  ),
  Job(
    title: 'Indian Navy - Sailor Entry 2026',
    organization: 'Indian Navy',
    location: 'All India',
    lastDate: '22 August 2026',
    category: 'Defence',
    applyLink: 'https://joinindiannavy.gov.in',
  ),

  // Teaching - Government
  Job(
    title: 'KVS Teacher Recruitment 2026 (PGT/TGT)',
    organization: 'Kendriya Vidyalaya Sangathan',
    location: 'All India',
    lastDate: '15 July 2026',
    category: 'Teaching',
    applyLink: 'https://kvsangathan.nic.in',
  ),
  Job(
    title: 'CTET 2026 - Central Teacher Eligibility Test',
    organization: 'CBSE',
    location: 'All India',
    lastDate: '20 July 2026',
    category: 'Teaching',
    applyLink: 'https://ctet.nic.in',
  ),
  Job(
    title: 'Primary Teacher Recruitment (DSSSB)',
    organization: 'Delhi Subordinate Services Selection Board',
    location: 'Delhi',
    lastDate: '22 July 2026',
    category: 'Teaching',
    applyLink: 'https://dsssb.delhi.gov.in',
  ),
  Job(
    title: 'Assistant Professor Recruitment - State University',
    organization: 'State Higher Education Department',
    location: 'All India',
    lastDate: '28 August 2026',
    category: 'Teaching',
    applyLink: 'https://ugc.gov.in',
  ),

  // Teaching - Private
  Job(
    title: 'Mathematics Teacher (Grade 9-10)',
    organization: 'Delhi Public School, Bangalore',
    location: 'Bangalore, Karnataka',
    lastDate: '10 July 2026',
    category: 'Teaching',
    applyLink: 'https://dpsbangalore.edu.in',
    isGovernment: false,
  ),
  Job(
    title: 'Pre-Primary Teacher (Montessori Trained)',
    organization: 'Kidzee Preschool',
    location: 'Pune, Maharashtra',
    lastDate: '12 July 2026',
    category: 'Teaching',
    applyLink: 'https://kidzee.com/careers',
    isGovernment: false,
  ),
  Job(
    title: 'Physics Faculty - Coaching Institute',
    organization: 'Aakash Institute',
    location: 'Kota, Rajasthan',
    lastDate: '25 July 2026',
    category: 'Teaching',
    applyLink: 'https://aakash.ac.in/careers',
    isGovernment: false,
  ),

  // Medical - Government
  Job(
    title: 'AIIMS Staff Nurse Recruitment 2026',
    organization: 'All India Institute of Medical Sciences',
    location: 'All India',
    lastDate: '28 July 2026',
    category: 'Medical',
    applyLink: 'https://aiims.edu',
  ),
  Job(
    title: 'ESIC Medical Officer Recruitment 2026',
    organization: 'Employees State Insurance Corporation',
    location: 'All India',
    lastDate: '05 August 2026',
    category: 'Medical',
    applyLink: 'https://esic.gov.in',
  ),
  Job(
    title: 'Staff Nurse Recruitment - District Hospitals',
    organization: 'State Health Department',
    location: 'All India',
    lastDate: '10 August 2026',
    category: 'Medical',
    applyLink: 'https://nhm.gov.in',
  ),
  Job(
    title: 'Lab Technician - Government Hospitals',
    organization: 'Ministry of Health and Family Welfare',
    location: 'All India',
    lastDate: '15 August 2026',
    category: 'Medical',
    applyLink: 'https://mohfw.gov.in',
  ),

  // Medical - Private
  Job(
    title: 'General Physician - Apollo Hospital',
    organization: 'Apollo Hospitals',
    location: 'Chennai, Tamil Nadu',
    lastDate: '15 July 2026',
    category: 'Medical',
    applyLink: 'https://apollohospitals.com/careers',
    isGovernment: false,
  ),
  Job(
    title: 'Staff Nurse - ICU Department',
    organization: 'Fortis Healthcare',
    location: 'Delhi NCR',
    lastDate: '20 July 2026',
    category: 'Medical',
    applyLink: 'https://fortishealthcare.com/careers',
    isGovernment: false,
  ),
  Job(
    title: 'Pharmacist - Retail Pharmacy Chain',
    organization: 'Apollo Pharmacy',
    location: 'Hyderabad, Telangana',
    lastDate: '18 July 2026',
    category: 'Medical',
    applyLink: 'https://apollopharmacy.in/careers',
    isGovernment: false,
  ),

  // Sports - Government
  Job(
    title: 'Sports Authority of India - Coach Recruitment',
    organization: 'Sports Authority of India',
    location: 'All India',
    lastDate: '20 August 2026',
    category: 'Sports',
    applyLink: 'https://sportsauthorityofindia.nic.in',
  ),
  Job(
    title: 'Indian Army Sports Quota Recruitment',
    organization: 'Indian Army',
    location: 'All India',
    lastDate: '25 August 2026',
    category: 'Sports',
    applyLink: 'https://joinindianarmy.nic.in',
  ),
  Job(
    title: 'Physical Education Teacher (PET) Recruitment',
    organization: 'State Education Department',
    location: 'All India',
    lastDate: '30 July 2026',
    category: 'Sports',
    applyLink: 'https://education.gov.in',
  ),

  // Sports - Private
  Job(
    title: 'Cricket Coach - Junior Academy',
    organization: 'MRF Pace Foundation',
    location: 'Chennai, Tamil Nadu',
    lastDate: '12 July 2026',
    category: 'Sports',
    applyLink: 'https://mrfpacefoundation.com',
    isGovernment: false,
  ),
  Job(
    title: 'Fitness Trainer - Gym Chain',
    organization: 'Cult.fit',
    location: 'Bangalore, Karnataka',
    lastDate: '15 July 2026',
    category: 'Sports',
    applyLink: 'https://cult.fit/careers',
    isGovernment: false,
  ),
  Job(
    title: 'Football Coach - Youth Academy',
    organization: 'Bhaichung Bhutia Football Schools',
    location: 'Kolkata, West Bengal',
    lastDate: '20 July 2026',
    category: 'Sports',
    applyLink: 'https://bbfs.in',
    isGovernment: false,
  ),
  // State-specific Government jobs
  Job(
    title: 'Maharashtra Police Constable Recruitment 2026',
    organization: 'Maharashtra State Police',
    location: 'Mumbai, Maharashtra',
    lastDate: '28 July 2026',
    category: 'Defence',
    applyLink: 'https://mahapolice.gov.in',
  ),
  Job(
    title: 'Uttar Pradesh Police SI Recruitment 2026',
    organization: 'UP Police Recruitment Board',
    location: 'Lucknow, Uttar Pradesh',
    lastDate: '05 August 2026',
    category: 'Defence',
    applyLink: 'https://uppbpb.gov.in',
  ),
  Job(
    title: 'Tamil Nadu TET 2026',
    organization: 'Teacher Recruitment Board, Tamil Nadu',
    location: 'Chennai, Tamil Nadu',
    lastDate: '15 July 2026',
    category: 'Teaching',
    applyLink: 'https://trb.tn.gov.in',
  ),
  Job(
    title: 'West Bengal SSC Clerkship 2026',
    organization: 'West Bengal Staff Selection Commission',
    location: 'Kolkata, West Bengal',
    lastDate: '22 July 2026',
    category: 'SSC',
    applyLink: 'https://wbssc.gov.in',
  ),
  Job(
    title: 'Karnataka Bank PO Recruitment 2026',
    organization: 'Karnataka Bank',
    location: 'Bangalore, Karnataka',
    lastDate: '10 August 2026',
    category: 'Banking',
    applyLink: 'https://karnatakabank.com/careers',
  ),
  Job(
    title: 'Bihar Staff Nurse Recruitment 2026',
    organization: 'Bihar Technical Service Commission',
    location: 'Patna, Bihar',
    lastDate: '18 July 2026',
    category: 'Medical',
    applyLink: 'https://btsc.bihar.gov.in',
  ),
  Job(
    title: 'Rajasthan Sports Quota Recruitment 2026',
    organization: 'Rajasthan Sports Council',
    location: 'Jaipur, Rajasthan',
    lastDate: '25 July 2026',
    category: 'Sports',
    applyLink: 'https://rajsports.rajasthan.gov.in',
  ),
];