import 'job_model.dart';

List<Job> sampleJobs = [
  Job(
    title: 'SSC CGL 2026 - Combined Graduate Level',
    organization: 'Staff Selection Commission',
    location: 'All India',
    lastDate: '30 June 2026',
    category: 'SSC',
    applyLink: 'https://ssc.gov.in',
  ),
  Job(
    title: 'RRB NTPC Graduate Level Posts',
    organization: 'Railway Recruitment Board',
    location: 'All India',
    lastDate: '15 July 2026',
    category: 'Railway',
    applyLink: 'https://indianrailways.gov.in',
  ),
  Job(
    title: 'UPSC Civil Services Examination 2026',
    organization: 'Union Public Service Commission',
    location: 'All India',
    lastDate: '10 August 2026',
    category: 'UPSC',
    applyLink: 'https://upsc.gov.in',
  ),
  Job(
    title: 'IBPS PO Recruitment 2026',
    organization: 'Institute of Banking Personnel Selection',
    location: 'All India',
    lastDate: '20 July 2026',
    category: 'Banking',
    applyLink: 'https://ibps.in',
  ),
  Job(
    title: 'Indian Army - Technical Entry Scheme',
    organization: 'Indian Army',
    location: 'All India',
    lastDate: '25 July 2026',
    category: 'Defence',
    applyLink: 'https://joinindianarmy.nic.in',
  ),
  Job(
    title: 'SSC CHSL 2026 - 10+2 Level Posts',
    organization: 'Staff Selection Commission',
    location: 'All India',
    lastDate: '05 August 2026',
    category: 'SSC',
    applyLink: 'https://ssc.gov.in',
  ),
  Job(
    title: 'RRB Group D Recruitment 2026',
    organization: 'Railway Recruitment Board',
    location: 'All India',
    lastDate: '12 August 2026',
    category: 'Railway',
    applyLink: 'https://indianrailways.gov.in',
  ),
  Job(
    title: 'SBI Clerk Recruitment 2026',
    organization: 'State Bank of India',
    location: 'All India',
    lastDate: '18 August 2026',
    category: 'Banking',
    applyLink: 'https://sbi.co.in/careers',
  ),
  Job(
    title: 'Indian Navy - Sailor Entry 2026',
    organization: 'Indian Navy',
    location: 'All India',
    lastDate: '22 August 2026',
    category: 'Defence',
    applyLink: 'https://joinindiannavy.gov.in',
  ),
  Job(
    title: 'UPSC NDA and NA Examination 2026',
    organization: 'Union Public Service Commission',
    location: 'All India',
    lastDate: '30 August 2026',
    category: 'UPSC',
    applyLink: 'https://upsc.gov.in',
  ),
];